name: CI - Registry

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      RELEASE_GO_VER: "1.23"

    steps:
    - name: Check out code
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: "Set up Go ${{ env.RELEASE_GO_VER }}"
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: "${{ env.RELEASE_GO_VER }}"
        check-latest: true
      id: go

    - name: Build
      run: make binaries

    - name: Registry - Distribution
      run: make ci-distribution

    - name: Registry - Zot
      run: make ci-zot
