name: CI - Registry

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      RELEASE_GO_VER: "1.23"

    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: "Set up Go ${{ env.RELEASE_GO_VER }}"
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: "${{ env.RELEASE_GO_VER }}"
        check-latest: true
      id: go

    - name: Build
      run: make binaries

    - name: Registry - Distribution
      run: make ci-distribution

    - name: Registry - Zot
      run: make ci-zot
